### PR TITLE
Update flash_player_sa_linux.x86_64.tar.gz to 32.0.0.270

### PR DESCRIPTION
**Pull request by eos-shell-build**
<i>(This pull request was automatically generated by [endlessm/flatpak-external-data-checker](https://github.com/endlessm/flatpak-external-data-checker). Please contact @wjt if you have any questions or complaints.)</i>

### CODE REVIEW

**Comment by wjt** [comment]
Something wrong with the version number scraping, @hadess ?

**Comment by hadess** [comment]
I don't see anything wrong with the version scraping either in the Flash Player .json, or in the flatpak-external-data-checker code. Maybe a problem in `_update_manifest`? Do you have the logs for the tool that generated this?

(By the way, we might want to separately make the same formatting changes the tool is making without changing the content, to reduce the delta. Could we have that tool in flatpak-external-data-checker?)

**Comment by hadess** [comment]
I made the test HTML checker print something out:
```
./test_htmlchecker.py 
DEBUG:checker:Checking module flashplayer (path: ./com.adobe.Flash-Player-Projector.json)
DEBUG:checker:Checking individual sources in ./com.adobe.Flash-Player-Projector.json
DEBUG:checker:[1/2] checking flash_player_sa_linux.x86_64.tar.gz
DEBUG:checkers.htmlchecker:Getting extra data info from https://www.adobe.com/support/flashplayer/debug_downloads.html; may take a while
DEBUG:checker:[2/2] checking com.adobe.Flash-Player-Projector.svg
DEBUG:checkers.htmlchecker:com.adobe.Flash-Player-Projector.svg is not a html type ext data
ExternalFile(url='https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz', checksum='f1fbdb9bd0f7235d6f6b6d589ad7be4eb1c230a357cfc27adf5d4712fdaf5b47', size=8693594, version='32.0.0.293', timestamp=datetime.datetime(2019, 11, 13, 4, 14, 9))
```

Should we have a check in the HTML checker that it throws an error in case the URL's content changed but not the version number? Is it possible that the HTML had the old version number?

**Comment by hadess** [comment]
This PR contains a working update:
https://github.com/flathub/com.adobe.Flash-Player-Projector/pull/29

We can continue the discussion here or in an issue filed against flatpak-external-data-checker.

**Comment by wjt** [comment]
https://github.com/endlessm/flatpak-external-data-checker/issues/36 is basically the same issue.

I noticed that `./flashplayer --version` reports the version, so in principle the checker could just run it. There's precedent for this – it runs AppImage files in a sandbox to unpack them and scrape the version number out of the `.desktop` file. In this case it'd need to arrange for an X display to be available, too… or it could be extracted with `strings` or `objdump`?

>  (By the way, we might want to separately make the same formatting changes the tool is making without changing the content, to reduce the delta. Could we have that tool in flatpak-external-data-checker?)

Sure, it's just a round-trip through json-glib (to get rid of non-standard syntax) and Python's `json` module, I'll cook a script.

**Comment by hadess** [comment]
> I noticed that `./flashplayer --version` reports the version, so in principle the checker could just run it. There's precedent for this – it runs AppImage files in a sandbox to unpack them and scrape the version number out of the `.desktop` file. In this case it'd need to arrange for an X display to be available, too… or it could be extracted with `strings` or `objdump`?

You'd need to unpack the tarball, run the software, replace the "," by ".". Gross. We still don't know whether the HTML content being wrong was the problem either. Let's not jump to conclusions.

**Pull request closed without merging**
