### PR TITLE
Update to 22.08

### PR DESCRIPTION
**Pull request by ColinKinloch**

### CODE REVIEW

**Comment by hadess** [comment]
Please split the changes into 2 commits, thanks.

**Comment by hadess** [comment]
I tested this, and the app crashes on exit after pressing the "Close" button in the "Samarost 2" user interface. It used to just throw criticals:
```
(flashplayer:2): GLib-GObject-WARNING **: 08:40:39.927: instance with invalid (NULL) class pointer
(flashplayer:2): GLib-GObject-CRITICAL **: 08:40:39.927: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by hadess** [comment]
There also seems to be a problem with the icons, which are now a number of times bigger than the original versions but with only a couple of lines of pixels added.

**Comment by ColinKinloch** [comment]
> There also seems to be a problem with the icons, which are now a number of times bigger than the original versions but with only a couple of lines of pixels added.

Specifically the SVG version? In what context is it bigger?

**Comment by ColinKinloch** [comment]
The current stable closes with
```
(flashplayer:2): GLib-GObject-CRITICAL **: 12:01:07.008: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

The SIGSEGV seems to occur around `g_signal_handlers_disconnect` as well.

**Comment by hadess** [comment]
> Specifically the SVG version? In what context is it bigger?

No, the PNGs are 3 times the file size.

**Comment by ColinKinloch** [comment]
Ah, I see. I added the pixels using GIMP...

I've switched to using the svg via rsvg-convert.

**Comment by hadess** [comment]
I'm moved the icons changes to https://github.com/flathub/com.adobe.Flash-Player-Projector/pull/59
Note that we don't use signed-off-bys here.

I'd like to find a work-around for the crash, as otherwise a bunch of preferences aren't saved IIRC, so I'll leave this open until I can find that work-around.

**Comment by Mershl** [comment]
No pressure. Just FYI. Flatpak started showing the following warning today:
```
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   com.adobe.Flash-Player-Projector
```

**Comment by ColinKinloch** [comment]
I don't like this solution, but it no segfaults.
I'm not sure what data flashplayer is calling `g_signal_handlers_disconnect_matched` with but `GSignalMatchType mask` is rarely a valid value.

**Comment by hadess** [comment]
I'd rather we figure out when `g_signal_handlers_disconnect_matched()` is called, and why the guard crashes. That means getting backtraces with debugging symbols, and/or disassembling the flash player with Ghidra. Blindly disabling the guard isn't an option.

**Comment by ColinKinloch** [comment]
You're right. I'll just detail things as I understand them in case I don't have time to fix it.

flashplayer calls `g_signal_handlers_disconnect_matched` with mostly non power of two ([invalid](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gobject/gsignal.h#L189-197)) `GSignalMatchType mask` values.

On `20.08` one call of `g_signal_handlers_disconnect_matched` fails the [`G_TYPE_CHECK_INSTANCE`](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gobject/gtype.c#L4192) check.
On `21.08` a call to `g_signal_handlers_disconnect_matched` has a value of `type_instance->g_class` appears to be outside accessible memory causing a segmentation fault. I assume these are the same calls.

**Comment by ColinKinloch** [comment]
```
==3== Invalid read of size 8
==3==    at 0x52CA9FD: g_type_check_instance (gtype.c:4199)
==3==    by 0x52BCE9B: g_signal_handlers_disconnect_matched (gsignal.c:3021)
==3==    by 0x883753: ??? (in /app/extra/flashplayer)
==3==    by 0x8837E7: ??? (in /app/extra/flashplayer)
==3==    by 0xA5A1E3: ??? (in /app/extra/flashplayer)
==3==    by 0xA57737: ??? (in /app/extra/flashplayer)
==3==    by 0xA57932: ??? (in /app/extra/flashplayer)
==3==    by 0xA57C07: ??? (in /app/extra/flashplayer)
==3==    by 0x805AFB: ??? (in /app/extra/flashplayer)
==3==    by 0x87B633: ??? (in /app/extra/flashplayer)
==3==    by 0x87B67B: ??? (in /app/extra/flashplayer)
==3==    by 0x87B6D8: ??? (in /app/extra/flashplayer)
==3==  Address 0xaaaaaaaaaaaaaaaa is not stack'd, malloc'd or (recently) free'd
==3== 
Application crashed with an unhandled SIGSEGV
```

**Comment by ColinKinloch** [comment]
I've patched `flashplayer` replacing the offending `gtk_widget_destroy` call with `NOP`.
The call appears to be used 3 times on exit.
Would a binary patch be an acceptable solution?
As flash is abandoned it likely will never need to changed.

**Comment by ColinKinloch** [comment]
The instruction at `0x8B0D43` is also executed once every time the right click menu is closed.

**Comment by hadess** [comment]
Wouldn't a patch like this against gtk2 work? We could build our own gtk2 for that purpose...

```diff
diff --git a/gobject/gsignal.c b/gobject/gsignal.c
index 32453bc51..e16d186a4 100644
--- a/gobject/gsignal.c
+++ b/gobject/gsignal.c
@@ -3058,8 +3058,9 @@ g_signal_handlers_disconnect_matched (gpointer         instance,
3058⋮3058│ {
3059⋮3059│   guint n_handlers = 0;
3060⋮3060│   
    ⋮3061│+  if ((mask & ~G_SIGNAL_MATCH_MASK) != 0)
    ⋮3062│+    return;
3061⋮3063│   g_return_val_if_fail (G_TYPE_CHECK_INSTANCE (instance), 0);
3062⋮    │-  g_return_val_if_fail ((mask & ~G_SIGNAL_MATCH_MASK) == 0, 0);
3063⋮3064│   
3064⋮3065│   if (mask & (G_SIGNAL_MATCH_CLOSURE | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA))
3065⋮3066│     {
```

Thanks @ColinKinloch for looking into that!

**Comment by hadess** [comment]
> Wouldn't a patch like this against gtk2 work? We could build our own gtk2 for that purpose...

I'm trying that in https://github.com/flathub/com.adobe.Flash-Player-Projector/pull/61

**Comment by ColinKinloch** [comment]
Sorry, I was wrong about mask being invalid.

**Comment by hadess** [comment]
> Sorry, I was wrong about mask being invalid.

Yeah, and I'm building a new gtk2 when the patch applies to glib. Must not have had enough coffee.

> I've patched `flashplayer` replacing the offending `gtk_widget_destroy` call with `NOP`.

I think this is easier to implement on the GTK side, and instead of neutering `gtk_widget_destroy`, we can neuter the crasher itself.

**Comment by ColinKinloch** [comment]
I'd assumed that valgrind was doing something special but it seems `instance->g_class` really is `0xaaaaaaaaaaaaaaaa`.
Is it something to do with [`MALLOC_PERTURB_`](https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html#index-glibc_002emalloc_002eperturb)?

**Comment by hadess** [comment]
> I'd assumed that valgrind was doing something special but it seems `instance->g_class` really is `0xaaaaaaaaaaaaaaaa`.

My guess is that it gets overwritten. By what, I have no idea. I have a slightly different version in https://github.com/flathub/com.adobe.Flash-Player-Projector/pull/61 which will keep track of the menu bar itself. Let me know what you think.

**Comment by ColinKinloch** [comment]
It's a nit pick but `GTK_IS_MENU_BAR (widget)` would be better than `g_strcmp0 (G_OBJECT_TYPE_NAME (widget), "GtkMenuBar") == 0)`.

**Comment by hadess** [comment]
Implemented in https://github.com/flathub/com.adobe.Flash-Player-Projector/pull/61

Thanks for your help!

**Pull request closed without merging**
